# Generated by Django 5.2.7 on 2025-10-23 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('disciplina', models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('ingles', 'Inglês'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biologia'), ('outra', 'Outra')], max_length=100)),
                ('horas_contratadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('saldo_horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
