# Generated by Django 5.2.7 on 2025-10-30 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('duracao', models.DecimalField(decimal_places=2, max_digits=4)),
                ('assunto', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='gestao_aulas.aluno')),
            ],
        ),
    ]
