# Generated by Django 5.2.7 on 2025-12-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_aulas', '0002_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana da aula fixa', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='horario_fixo',
            field=models.TimeField(blank=True, help_text='Horário padrão da aula', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='hora_aula',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
