# Generated by Django 5.2.7 on 2025-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_professor_telefone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='professor',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='disciplinas',
            field=models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('ingles', 'Inglês'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biologia'), ('outra', 'Outra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
