# Generated by Django 5.2.7 on 2025-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_professor_managers_alter_professor_disciplinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplinas',
            field=models.CharField(help_text='Separe as disciplinas por vírgula', max_length=255),
        ),
    ]
